image: "python:3.8-slim"

before_script:
  - pip install poetry==1.0.5
  - poetry install --no-interaction --no-ansi --no-root

test:
  script:
    - poetry run pytest
    - poetry run safety check
    - poetry run pylint citest
