steps:
  - name: 'gcr.io/$PROJECT_ID/python:3.8-poetry1.0.5'
    id: Test
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        poetry install --no-interaction --no-ansi --no-root && \
        poetry run pytest && \
        poetry run safety check && \
        poetry run pylint citest && \
        poetry build

  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/citest:$BRANCH_NAME', '.']
images:
  - 'gcr.io/$PROJECT_ID/citest:$BRANCH_NAME'
