FROM python:3.8-slim as base

RUN pip install "poetry==1.0.5"

WORKDIR /code
COPY poetry.lock pyproject.toml /code/

RUN poetry install --no-interaction --no-ansi --no-root

COPY . /code

# Run test suite
RUN poetry run pytest && poetry run safety check

# Run the linter (CI only)
RUN poetry run pylint citest

# Build
RUN poetry build
