# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install poetry and dependencies
      run: |
        pip install -U pip
        pip install poetry==1.1.0
        poetry install

    - name: Run linter
      run: poetry run pylint citest

    - name: Run tests
      run: poetry run pytest

    - name: Run vulnerability check
      run: poetry run safety check
