# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: install build libraries
      uses: abatilo/actions-poetry@v1.0.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.5
        args: install

    - name: Run tests
      uses: abatilo/actions-poetry@v1.0.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.5
        args: run pytest
        
    - name: check for vulnerabilities
      uses: abatilo/actions-poetry@v1.0.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.5
        args: run safety
    
